#!/usr/bin/env ruby
repo="sickp/alpine-ruby"

ruby_version = ARGV.first || ''
md = ruby_version.match(/\A(((\d+)\.\d+)\.\d+)-r\d+\z/)
case md && md[3]
when '2'
  tags = [ md[1], md[2], md[3], 'latest' ]
else
  puts "Usage: build {major}.{minor}.{teeny}-r{revision}"
  exit 1
end

system("docker image build -t #{repo}:#{ruby_version} --pull versions/#{ruby_version}") || abort
puts "Built #{repo}:#{ruby_version}"

tags.each do |tag|
  system("docker image tag #{repo}:#{ruby_version} #{repo}:#{tag}") || abort
  puts "Tagged #{repo}:#{tag}"
end
