#!/bin/bash
set -e
repo="sickp/alpine-ruby"
latest=$(ls -r versions | head -1)
version=${1:-$latest}

docker build -t ${repo}:${version} --pull versions/${version}
echo "=> Built ${repo}:${version}"
if [[ $latest == $version ]]; then
  tags="2.2 2 latest"
  for tag in ${tags}; do
    docker tag -f ${repo}:${version} ${repo}:${tag}
    echo "=> Tagged ${repo}:${tag}"
  done
fi
