#!/usr/bin/env ruby
repo="sickp/alpine-ruby"

ruby_version = ARGV.first
case ruby_version
when /\A2.4.0-r\d+\z/
  tags = %w(2.4.0 2.4 2 latest)
else
  puts "Usage: build {major}.{minor}.{teeny}-r{revision}"
  exit 1
end

system("docker image build -t #{repo}:#{ruby_version} --pull versions/#{ruby_version}") || abort
puts "Built #{repo}:#{ruby_version}"

tags.each do |tag|
  system("docker image tag #{repo}:#{ruby_version} #{repo}:#{tag}") || abort
  puts "Tagged #{repo}:#{tag}"
end
