#!/usr/bin/env ruby
repo="sickp/alpine-ruby"

ruby_version = ARGV.first || ''
md = ruby_version.match(/\A(((\d+)\.\d+)\.\d+)-r\d+\z/)
case md && md[3]
when '2'
  tags = [ md[1], md[2], md[3], 'latest' ]
else
  puts "Usage: push {major}.{minor}.{teeny}-r{revision}"
  exit 1
end

tags.unshift(ruby_version)

tags.each do |tag|
  system("docker image push #{repo}:#{tag}") || abort
  puts "Pushed #{repo}:#{tag}"
end
