#!/usr/bin/env ruby
repo="sickp/alpine-ruby"

ruby_version = ARGV.first
case ruby_version
when /\A2.4.0-r\d+\z/
  tags = %w(2.4.0 2.4 2 latest)
else
  puts "Usage: push {major}.{minor}.{teeny}-r{revision}"
  exit 1
end

tags.unshift(ruby_version)

tags.each do |tag|
  system("docker image push #{repo}:#{tag}") || abort
  puts "Pushed #{repo}:#{tag}"
end
